### ISSUE TITLE
Reopen all dialogues if the orientation is changed

### ISSUE THREAD

**Issue by asterix11** [Cedgetec/SchulinfoApp-android#52]
For every user it is annoying if he has to refill a form inside a dialog, because it is closed when changing the orientation.

**Comment by asterix11** [comment]
!!!IMPORTANT!!!

**Comment by asterix11** [comment]
UNTIL: 8 o'clock PM

**Comment by LRAnimations** [comment]
Textdialogs still close on orientation change.

**Comment by LRAnimations** [comment]
Delete dialogs still close on orientation change in filter activity.
