### ISSUE TITLE
Scrollposition wiederherstellen

### ISSUE THREAD

**Issue by lazylazyllama** [Cedgetec/SchulinfoApp-android#74]
Wenn man das Gerät dreht, wäre es gut, wenn die vorherige Scrollposition beibehalten werden würde. 

In den Einstellungen und in der Filter Activity geht es bereits.
Im Vertretungsplan und im Klausurenplan sollte es noch ergänzt werden.

**Comment by Wasserbroetchen** [comment]
Settings wurden von Google gefixt :)
