### ISSUE TITLE
Spaces are left out while parsing sentences

### ISSUE THREAD

**Issue by Lennart16** [Cedgetec/SchulinfoApp-android#78]
Occasionally this happens in sentences that the app is parsing: 

![gaga](https://cloud.githubusercontent.com/assets/10562711/22026773/0bf9e550-dcd2-11e6-84c0-34fac047a87a.png)

while the original shows the correct sentence:

![gaga](https://cloud.githubusercontent.com/assets/10562711/22026823/2f8384f4-dcd2-11e6-8995-ada5cfb62117.png)

**Comment by Gebatzens** [comment]
Fixed on server side.
